// 1) Global CSS for react-loading-skeleton
import 'react-loading-skeleton/dist/skeleton.css';

// Your existing global styles
import './globals.scss';

// Google Font (Next.js 13.5.6)
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

// Metadata used by Next.js (typed for clarity)
export const metadata: Metadata = {
  title: 'Libelit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // NOTE: Use real JSX tags here (no HTML entities)
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}