// 1) Global CSS for react-loading-skeleton
import 'react-loading-skeleton/dist/skeleton.css';

// Your existing global styles and font import
import './globals.scss';
import { Inter } from '@next/font/google';
import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

// (optional but recommended: type the metadata export)
export const metadata: Metadata = {
  title: 'Libelit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 2) Use real JSX tags (no HTML entities)
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}